events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        location /metrics {
            stub_status on;
            allow 127.0.0.1;
            allow 172.16.0.0/12;
            allow 192.168.0.0/16;
            deny all;
        }
    }
}
