tunnel: 82377467-2594-41e3-a760-84c64a788819
credentials-file: /home/mandar/.cloudflared/82377467-2594-41e3-a760-84c64a788819.json

ingress:
  - hostname: auth.writesomething.fun
    service: http://localhost:8080
  - hostname: authadmin.writesomething.fun
    service: http://localhost:3000
  - hostname: wiki.writesomething.fun
    service: http://localhost:8090
  - hostname: skribbl.writesomething.fun
    service: http://127.0.0.1:5002
  - service: http_status:404
