tunnel: 82377467-2594-41e3-a760-84c64a788819
credentials-file: /etc/cloudflared/82377467-2594-41e3-a760-84c64a788819.json

ingress:
  - hostname: writesomething.fun
    service: http://127.0.0.1:8000
  - hostname: dump.writesomething.fun
    service: http://127.0.0.1:4000
  - hostname: radio.writesomething.fun
    service: http://127.0.0.1:8090
  - hostname: server.writesomething.fun
    service: http://127.0.0.1:3031
  - hostname: draw.writesomething.fun
    service: http://127.0.0.1:5000
  - hostname: collab.writesomething.fun
    service: http://127.0.0.1:5001
  - hostname: skribbl.writesomething.fun
    service: http://127.0.0.1:5002
  - hostname: claw.writesomething.fun
    service: http://127.0.0.1:42618
  - hostname: auth.writesomething.fun
    service: http://localhost:8080
  - hostname: authadmin.writesomething.fun
    service: http://localhost:3000
  - hostname: wiki.writesomething.fun
    service: http://127.0.0.1:8090
  - service: http_status:404
